version: '5'

services:

  mqa-score:
    image: mqa-scoring:v1.0.0
    container_name: mqa-score
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - '127.0.0.1:8000:8000'
    environment:
      - PORT=8000
      - MINIO_URL=play.min.io
      - MINIO_ACCESS_KEY=Q3AM3UQ867SPQQA43P2F
      - MINIO_SECRET_KEY=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
    networks:
      - mqa-network

  mongodb:
    container_name: mongodb-mqa
    image: mongo:4.2
    # command: --nojournal
    command: mongod --port 27020
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_PASSWORD=BeOpen2023!
    ports:
      - '27020:27020'
    volumes: 
      - ./data:/data/db
    networks:
      - mqa-network

networks:
  mqa-network:
    driver: bridge