version: '5'

services:

  mqa-score:
    container_name: mqa-score
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - '127.0.0.1:8000:8000'
    environment:
      - PORT=8000
      - MINIO_URL=minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=BeOp3nPassword
      - MINIO_ACTIVE=true
      - MINIO_SECURE=false
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=BeOpen2023!
    networks:
      - mqa-network

  mongodb:
    container_name: mongodb-mqa
    image: mongo:4.4
    # command: --nojournal
    command: mongod --port 27020
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_PASSWORD=BeOpen2023!
    ports:
      - '27020:27020'
    volumes: 
      - ./data:/data/db
    networks:
      - mqa-network

  minio:
    image: minio/minio
    #restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    #volumes:
    #  - ./minio-storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: BeOp3nPassword
      #MINIO_BROWSER_REDIRECT_URL: http://localhost:9001/minio/
      MINIO_IDENTITY_OPENID_CONFIG_URL: https://platform.beopendep.it/auth/realms/master/.well-known/openid-configuration
      MINIO_BROWSER_REDIRECT_URL: 'http://localhost:9001'
      MINIO_IDENTITY_OPENID_CLIENT_ID: minio-app
      MINIO_IDENTITY_OPENID_CLIENT_SECRET: W9qhXVr3iou2ry6YIOSlQIHpBTtd1KUb
      MINIO_IDENTITY_OPENID_SCOPES: 'openid profile email'
      MINIO_IDENTITY_OPENID_CLAIM_NAME: policy
      MINIO_IDENTITY_OPENID_REDIRECT_URI: http://localhost:9001/oauth_callback
    command: server --console-address ":9001" /data
    networks:
      - mqa-network

networks:
  mqa-network:
    driver: bridge