version: '3'

services:

  ucc-eu:
    image: beopen/mqa-scoring:v1.0.0
    container_name: mqa-score
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - '127.0.0.1:8000:8000'
    environment:
      - PORT=8000